services:
  whisper-cuda-kannada:
    image: fedirz/faster-whisper-server:latest-cuda
    restart: unless-stopped
    ports:
      - 11800:11800
    volumes:
      - hugging_face_cache:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    environment:
      - WHISPER__MODEL=ARTPARK-IISc/whisper-small-vaani-kannada
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=11800
volumes:
  hugging_face_cache:
    driver: local
    driver_opts:
      type: none
      device: ~/.cache/huggingface
      o: bind
